### ISSUE TITLE
cachix : command not found

### ISSUE THREAD

**Issue by Trevoke** [purcell/setup-emacs#35] opened 2023-03-01 17:21 UTC
Running into an error which ... Is probably upstream from you? But I think I shouldn't skip steps in working my way up anyway, so, if this is upstream from you, sorry, but then I can point upstream to this issue when I go up... :) 

https://github.com/Trevoke/org-gtd.el/actions/runs/4304534917/jobs/7509572815#step:2:225

> /home/runner/work/_actions/purcell/setup-emacs/v3.0/dist/install-nix.sh: line 53: cachix: command not found
> Error: Command failed: /home/runner/work/_actions/purcell/setup-emacs/v3.0/dist/install-nix.sh emacs-27-2

**Comment by jcs090218** [comment] 2023-03-01 19:25
Duplicate of #33. Try use the latest version on the master branch.

**Closed** 2023-03-01 20:33 UTC

**Comment by purcell** [comment] 2023-03-02 10:17
That's a good point though, I didn't actually tag a fresh release, so I've done that now.

**Comment by mcraveiro** [comment] 2023-08-03 22:24
I've also been bitten by this. The problem seems to be that whilst there is a v4 tag, it does not show up under "releases":

![Screenshot from 2023-08-03 23-23-02](https://github.com/purcell/setup-emacs/assets/180654/151f44e5-50ea-4b5c-82ce-1289d4b92043)

**Comment by purcell** [comment] 2023-08-04 06:16
Good catch, thanks @mcraveiro — I've created a Release too now.

**Comment by purcell** [comment] 2023-08-04 06:21
P.S. If you're wondering why I didn't spot these issues earlier, it's because I use — and typically recommend – `setup-emacs@master` in my own projects. But I recognise it's reasonable for others to prefer specific versions and use Dependabot to get updates, so I'll try to remember to cut releases more often in future when bugs are fixed.
